--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/BetterRewards
build-by-default: true
branches:
- PM5
- PM4
projects:
  BetterRewards:
    path: ""
    icon: "icon-btrewards.png"
    libs:
      - src: ACM-PocketMine-MP/FormsUI/FormsUI
        version: ^1.1.4
      - src: ACM-PocketMine-MP/Commando/Commando
        version: ^4.0.0
        branch: PM5
      - src: muqsit/simplepackethandler/SimplePacketHandler
        version: ^0.1.5
      - src: muqsit/InvMenu/InvMenu
        version: ^4.7.3
        branch: "pm5"
      - src: ACM-PocketMine-MP/libPiggyUpdateChecker/libPiggyUpdateChecker
        version: ^2.0.0
      - src: poggit/libasynql/libasynql
        version: ^4.2.0
        branch: "master"
    lint:
      phpstan: false
...
